version: '2'
services:
 
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token <YOUR_TUNNEL_TOKEN>
    network_mode: host
    volumes:
      - ./config/cloudflare/config.yml:/etc/cloudflared/config.yml:ro



  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ./config/jellyfin:/config
      - ./media:/media
    ports:
      - "8096:8096"
    environment:
      - TZ=Asia/Muscat

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    volumes:
      - ./config/radarr:/config
      - ./media:/media
      - ./downloads:/downloads
    ports:
      - 7878:7878
    environment:
      - TZ=Asia/Muscat

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ./config/sonarr:/config
      - ./media:/media
      - ./downloads:/downloads
    ports:
      - "8989:8989/tcp"
    environment:
      - TZ=Asia/Muscat

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    volumes:
      - ./config/jackett:/config
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Muscat

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Muscat

